/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    '(Copy)': typeof import('./src/components/product (Copy).vue')['default']
    AccordionCategories: typeof import('./src/components/accordionCategories.vue')['default']
    DesktopHero: typeof import('./src/components/desktopHero.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    HeroMobile: typeof import('./src/components/HeroMobile.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Order: typeof import('./src/components/order.vue')['default']
    Product: typeof import('./src/components/product.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
